name: Clone and Publish Docker Image

on:
  push:
    branches:
      - main # 触发的分支，可以根据需要修改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Clone the external repository
        run: git clone https://github.com/crazy-max/docker-flarum.git

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # 需要再 docker hub 中去创建 token,然后填写到secrets中 (docker hub token)
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make modifications
        run: |
          cd docker-flarum
          # 在以ENTRYPOINT开始的行前面插入内容
          awk '/^ENTRYPOINT/ { system("cat ../plugin"); } { print }' Dockerfile > file.tmp && mv file.tmp Dockerfile
      - name: Add plugin
        run: |
          ls -al
          pwd
      - name: Build and Push Container image
        uses: docker/build-push-action@v6
        with:
          context: ./docker-flarum
          push: true
          tags: qqzsc/dockerflarum:latest
