name: Clone and Publish Docker Image

on:
  push:
    branches:
      - main # 触发的分支，可以根据需要修改
  schedule:
    - cron: "0 0 */15 * *" # 每 15 天构建一次
permissions:
  contents: write
env:
  REGISTRY_URL: ccr.ccs.tencentyun.com
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone the external repository
        run: git clone https://github.com/crazy-max/docker-flarum.git

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # 需要再 docker hub 中去创建 token,然后填写到secrets中 (docker hub token)
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 利用 bash 命令, 在以ENTRYPOINT开始的行前面插入内容
      # (记住,github action 每一个阶段的初始目录都是项目的根目录)
      - name: Make modifications
        run: |
          cd docker-flarum
          awk '/^ENTRYPOINT/ { system("cat ../plugin"); } { print }' Dockerfile > file.tmp && mv file.tmp Dockerfile

      ### 把 flarum 镜像推送到docker hub
      - name: Build and Push Container image
        uses: docker/build-push-action@v6
        with:
          context: ./docker-flarum
          push: true
          platforms: linux/amd64
          tags: qqzsc/docker-flarum:latest
          # 这个参数可以把镜像加载到本地(此时platform 只能传递了一个平台) , 这样后面我们就不用编译了
          load: true
      - name: show docker image
        run: |
          docker images
          echo "-------------------------------------"
      ### 切换到腾讯云
      - name: Login to Tencent Cloud
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.TX_USERNAME }}
          password: ${{ secrets.TX_PASSWORD }}
      - name: Sync Docker Image(tengxun云)
        env:
          FROM_IMAGE: qqzsc/docker-flarum:latest
          TO_IMAGE: ccr.ccs.tencentyun.com/zscgoweb/docker-flarum:latest
        run: |
          docker tag  ${{ env.FROM_IMAGE }} ${{ env.TO_IMAGE }}
          docker push ${{ env.TO_IMAGE }}

      ##################### (腾讯云) ################################
      # 切换到 腾讯云(居然不可以直接登录) (好像不能直接命令行登录)
      # docker login ${{ env.REGISTRY_URL }} --username ${{ secrets.TX_USERNAME }} --password-stdin  ${{ secrets.TX_PASSWORD }}
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY_URL }}
      #     username: ${{ secrets.TX_USERNAME }}
      #     password: ${{ secrets.TX_PASSWORD }}

      # 腾讯的有命名空间(可以多个) ----这个空间下面可以放很多镜像(也可以成为一个仓库), 一个镜像下面有多个版本,注意区别
      ### 如果涉及到多个注册地, 建议把地址也加上,分的清楚,默认为 docker.io
      # - name: Login to Tencent Cloud
      #   env:
      #     FROM_IMAGE: docker.io/qqzsc/docker-flarum:latest
      #     TO_IMAGE: ccr.ccs.tencentyun.com/zscgoweb/docker-flarum:latest
      #   run: |
      #     docker pull ${{ env.FROM_IMAGE }}
      #     docker tag  ${{ env.FROM_IMAGE }} ${{ env.TO_IMAGE }}
      #     docker push ${{ env.TO_IMAGE }}
